// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAeQdRZWvQNTnTUin2aSVq5xNbHM0wwXQ',
    appId: '1:389318188928:web:11c3aeb5d02dd86fd72b65',
    messagingSenderId: '389318188928',
    projectId: 'test-73377',
    authDomain: 'test-73377.firebaseapp.com',
    storageBucket: 'test-73377.firebasestorage.app',
    measurementId: 'G-FXB5MEQJCS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbehx5HT3OSMdcQ9YVFBPsnI0zxUH-5lw',
    appId: '1:389318188928:android:e344e2cd39a9721bd72b65',
    messagingSenderId: '389318188928',
    projectId: 'test-73377',
    storageBucket: 'test-73377.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwmycuNTySi9bzqpDtpsgKrjOl_zOykgY',
    appId: '1:389318188928:ios:346652bdeeca785ed72b65',
    messagingSenderId: '389318188928',
    projectId: 'test-73377',
    storageBucket: 'test-73377.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwmycuNTySi9bzqpDtpsgKrjOl_zOykgY',
    appId: '1:389318188928:ios:346652bdeeca785ed72b65',
    messagingSenderId: '389318188928',
    projectId: 'test-73377',
    storageBucket: 'test-73377.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAeQdRZWvQNTnTUin2aSVq5xNbHM0wwXQ',
    appId: '1:389318188928:web:11d84f45e8468075d72b65',
    messagingSenderId: '389318188928',
    projectId: 'test-73377',
    authDomain: 'test-73377.firebaseapp.com',
    storageBucket: 'test-73377.firebasestorage.app',
    measurementId: 'G-G7FF91VC9L',
  );
}
